set_property -dict {PACKAGE_PIN T17  IOSTANDARD LVCMOS33} [get_ports {clk}]

set_property -dict {PACKAGE_PIN R2   IOSTANDARD LVCMOS33} [get_ports {opcode[7]}]
set_property -dict {PACKAGE_PIN T1   IOSTANDARD LVCMOS33} [get_ports {opcode[6]}]
set_property -dict {PACKAGE_PIN U1   IOSTANDARD LVCMOS33} [get_ports {opcode[5]}]
set_property -dict {PACKAGE_PIN W2   IOSTANDARD LVCMOS33} [get_ports {opcode[4]}]
set_property -dict {PACKAGE_PIN R3   IOSTANDARD LVCMOS33} [get_ports {opcode[3]}]
set_property -dict {PACKAGE_PIN T2   IOSTANDARD LVCMOS33} [get_ports {opcode[2]}]
set_property -dict {PACKAGE_PIN T3   IOSTANDARD LVCMOS33} [get_ports {opcode[1]}]
set_property -dict {PACKAGE_PIN V2   IOSTANDARD LVCMOS33} [get_ports {opcode[0]}]

set_property -dict {PACKAGE_PIN W13  IOSTANDARD LVCMOS33} [get_ports {immediate[7]}]
set_property -dict {PACKAGE_PIN W14  IOSTANDARD LVCMOS33} [get_ports {immediate[6]}]
set_property -dict {PACKAGE_PIN V15  IOSTANDARD LVCMOS33} [get_ports {immediate[5]}]
set_property -dict {PACKAGE_PIN W15  IOSTANDARD LVCMOS33} [get_ports {immediate[4]}]
set_property -dict {PACKAGE_PIN W17  IOSTANDARD LVCMOS33} [get_ports {immediate[3]}]
set_property -dict {PACKAGE_PIN W16  IOSTANDARD LVCMOS33} [get_ports {immediate[2]}]
set_property -dict {PACKAGE_PIN V16  IOSTANDARD LVCMOS33} [get_ports {immediate[1]}]
set_property -dict {PACKAGE_PIN V17  IOSTANDARD LVCMOS33} [get_ports {immediate[0]}]

set_property -dict {PACKAGE_PIN L1  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[7]}]
set_property -dict {PACKAGE_PIN P1  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[6]}]
set_property -dict {PACKAGE_PIN N3  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[5]}]
set_property -dict {PACKAGE_PIN P3  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[4]}]
set_property -dict {PACKAGE_PIN U3  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[3]}]
set_property -dict {PACKAGE_PIN W3  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[2]}]
set_property -dict {PACKAGE_PIN V3  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[1]}]
set_property -dict {PACKAGE_PIN V13  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_a[0]}]

set_property -dict {PACKAGE_PIN V14  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[7]}]
set_property -dict {PACKAGE_PIN U14  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[6]}]
set_property -dict {PACKAGE_PIN U15  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[5]}]
set_property -dict {PACKAGE_PIN W18  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[4]}]
set_property -dict {PACKAGE_PIN V19  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[3]}]
set_property -dict {PACKAGE_PIN U19  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[2]}]
set_property -dict {PACKAGE_PIN E19  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[1]}]
set_property -dict {PACKAGE_PIN U16  IOSTANDARD LVCMOS33} [get_ports {debug_output_reg_b[0]}]
