set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {clk}]

set_property -dict {PACKAGE_PIN R2   IOSTANDARD LVCMOS33} [get_ports {input_opcode[7]}]
set_property -dict {PACKAGE_PIN T1   IOSTANDARD LVCMOS33} [get_ports {input_opcode[6]}]
set_property -dict {PACKAGE_PIN U1   IOSTANDARD LVCMOS33} [get_ports {input_opcode[5]}]
set_property -dict {PACKAGE_PIN W2   IOSTANDARD LVCMOS33} [get_ports {input_opcode[4]}]
set_property -dict {PACKAGE_PIN R3   IOSTANDARD LVCMOS33} [get_ports {input_opcode[3]}]
set_property -dict {PACKAGE_PIN T2   IOSTANDARD LVCMOS33} [get_ports {input_opcode[2]}]
set_property -dict {PACKAGE_PIN T3   IOSTANDARD LVCMOS33} [get_ports {input_opcode[1]}]
set_property -dict {PACKAGE_PIN V2   IOSTANDARD LVCMOS33} [get_ports {input_opcode[0]}]

set_property -dict {PACKAGE_PIN W13  IOSTANDARD LVCMOS33} [get_ports {input_immediate[7]}]
set_property -dict {PACKAGE_PIN W14  IOSTANDARD LVCMOS33} [get_ports {input_immediate[6]}]
set_property -dict {PACKAGE_PIN V15  IOSTANDARD LVCMOS33} [get_ports {input_immediate[5]}]
set_property -dict {PACKAGE_PIN W15  IOSTANDARD LVCMOS33} [get_ports {input_immediate[4]}]
set_property -dict {PACKAGE_PIN W17  IOSTANDARD LVCMOS33} [get_ports {input_immediate[3]}]
set_property -dict {PACKAGE_PIN W16  IOSTANDARD LVCMOS33} [get_ports {input_immediate[2]}]
set_property -dict {PACKAGE_PIN V16  IOSTANDARD LVCMOS33} [get_ports {input_immediate[1]}]
set_property -dict {PACKAGE_PIN V17  IOSTANDARD LVCMOS33} [get_ports {input_immediate[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property -dict {PACKAGE_PIN W5  IOSTANDARD LVCMOS33} [get_ports {seven_seg_clk}]

set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS33} [get_ports {seven_seg_led[0]}]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS33} [get_ports {seven_seg_led[1]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS33} [get_ports {seven_seg_led[2]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports {seven_seg_led[3]}]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports {seven_seg_led[4]}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports {seven_seg_led[5]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports {seven_seg_led[6]}]

set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports {seven_seg_on[0]}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports {seven_seg_on[1]}]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports {seven_seg_on[2]}]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS33} [get_ports {seven_seg_on[3]}]

set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {a_greater_b}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports {a_equal_b}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {a_lesser_b}]
